import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import zlib from 'node:zlib'

const here = path.dirname(fileURLToPath(import.meta.url))

/**
 * The two halves of the module, both generated by build/java_fmt_teavm/build.sh.
 *
 * `java_fmt.runtime.mjs` is TeaVM's generated runtime: it supplies the module's
 * imports and the string and exception bridges, so the wasm is not standalone
 * and cannot be run by `wasmtime`. It ships verbatim.
 *
 * `java_fmt.wasm.br` is the module. It is stored brotli-compressed because
 * 3.3MB of WasmGC packs to 0.8MB, and node:zlib decompresses it once per
 * process, so the saving costs an install nothing and adds no dependency.
 *
 * One directory up from this file resolves to the package root whether we are
 * running from `dist` (published) or from `src` (tests), so the same path works
 * in both.
 */
const RUNTIME = path.join(here, '..', 'java_fmt.runtime.mjs')
const ARTIFACT = path.join(here, '..', 'java_fmt.wasm.br')

/** TeaVM's runtime module, whose `load` compiles and instantiates the wasm. */
type Runtime = {
  load: (source: ArrayBuffer, options: Record<string, unknown>) => Promise<{ exports: Record<string, unknown> }>
}

/** Decompresses the artifact into the buffer `load` compiles. */
const readArtifact = (): ArrayBuffer => {
  if (!fs.existsSync(ARTIFACT)) {
    throw new Error(
      `java_fmt.wasm.br is missing from ${path.dirname(ARTIFACT)}. It is committed to the repository and ships ` +
        'inside the published package, so this usually means a partial checkout; ' +
        'build/java_fmt_teavm/build.sh regenerates it.',
    )
  }

  const wasm = zlib.brotliDecompressSync(fs.readFileSync(ARTIFACT))
  // Slice to the exact bytes: a Buffer's `.buffer` is only the whole file when
  // it happens to be unpooled.
  return wasm.buffer.slice(wasm.byteOffset, wasm.byteOffset + wasm.byteLength) as ArrayBuffer
}

/**
 * Compiles and instantiates the module, resolving to its exports.
 *
 * The runtime's `load` takes either a path or the bytes themselves. It gets the
 * bytes: handed a path it reads the file through `fs.promises.open` and a web
 * stream, which leaves a handle Node counts as live, so a process that formatted
 * anything would never exit.
 */
export const loadModule = async (): Promise<Record<string, unknown>> => {
  const runtime = (await import(pathToFileURL(RUNTIME).href)) as Runtime
  const { exports } = await runtime.load(readArtifact(), {})
  return exports
}
